import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "./components/shared/Header";
import { Footer } from "./components/shared/Footer";
import { validateAccessToken } from 'app/utils/auth/validateAccessToken'

import "app/sass/global.sass";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Future world",
  description: "Generated by create next app",
};

export default async function RootLayout({ 
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const customer = await validateAccessToken();
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>

        <Header customer={customer}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
